name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify Secrets with PowerShell
        run: |
          if ($env:HEROKU_API_KEY) { Write-Host "HEROKU_API_KEY is set" } else { Write-Error "HEROKU_API_KEY is not set" }
          if ($env:HEROKU_EMAIL) { Write-Host "HEROKU_EMAIL is set" } else { Write-Error "HEROKU_EMAIL is not set" }
          if ($env:SSH_PRIVATE_KEY) { Write-Host "SSH_PRIVATE_KEY is set" } else { Write-Error "SSH_PRIVATE_KEY is not set" }
        shell: pwsh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=${{ secrets.HEROKU_EMAIL }} --password-stdin registry.heroku.com
          git remote add heroku https://git.heroku.com/dataanalyseweb.git
          git push heroku master
