name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Aktualisierte Version

    - name: Set up Python
      uses: actions/setup-python@v4 # Aktualisierte Version
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      run: |
        echo ${HEROKU_API_KEY} | docker login --username=${HEROKU_EMAIL} --password-stdin registry.heroku.com
        git remote add heroku https://git.heroku.com/dataanalyseweb.git
        git push heroku master
